version: '3'
services:
  front_app:
    build:
      context: ./frontend
    container_name: chatVRM
    ports:
      - 8080:8080
      - 3000:3000
      - 80:80
      - 443:443
    tty: true # コンテナの起動永続化
    volumes:
      - ./frontend:/workspace
    command: sh -c "bash create_certificates.sh && npm install && npm run dev:proxy"
    networks:
      - nginx_network
  uec_qa:
    build: ./backend/qa_api
    working_dir: /qa_api
    tty: true
    ports: 
      - "12344:12344"
    volumes:
      - ./backend/qa_api:/qa_api
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 12344 --proxy-headers"
    networks:
      - nginx_network
    env_file:
      - ./frontend/.env.local
  scrape_uec_info:
    build: ./backend/scrape_uec_info
    working_dir: /scrape_uec_info
    tty: true
    volumes:
      - ./backend/scrape_uec_info:/scrape_uec_info

networks:
  nginx_network:
    driver: bridge
